### ISSUE TITLE
Terminal UI required fixes

### ISSUE THREAD

**Issue by jug-dev** [Haidra-Org/AI-Horde-Worker#127]
- [x] Confirm terminal ui works on Linux.
- [x] Fix stdout/stderr suppression on Linux
- [ ] Fix kudos per hour in alchemy worker.
- [x] Move CPU Load over to the left. [2]
- [x] Fix kudos per hour setting if it's configured badly and terminal ui is enabled.
- [x] Check all input prompts respect the "always_download" config setting. (They don't [1])
- [x] Don't read the log file, hook Loguru directly.
- [x] Don't allow terminal ui to start if auto-download option is not selected. Unless run in parallel mode.
- [x] Confirm works with alchemy worker

[1] They don't, but it doesn't matter as these prompts happen before the UI is initialised.

**Comment by vadi2** [comment]
It struggles on Linux:

[Screencast from 26-03-23 11:04:33.webm](https://user-images.githubusercontent.com/110988/227765890-b2d03d75-f028-4d1b-ab60-88d248190e30.webm)

**Comment by jug-dev** [comment]
> It struggles on Linux:

Hopefully fixed now.

**Comment by vadi2** [comment]
Yep it is.
