### ISSUE TITLE
Use of folder 'nataili' causes package conflicts

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/AI-Horde-Worker#151]
While #149 was being drafted, it was discovered the folder for models, `nataili/` causes certain unintended behavior with ruff. In this particular case `ruff` fails to navigate import sorting, failing silently locally, and causes issues during CI. 

This only highlights the issue of using this folder with this project's folder/file structure, and could cause more problems in the future.

I am proposing the following high-level set of changes:

- Code which identifies users who are using the default folder scheme (ie, users with `./` as `NATAILI_CACHE_DIR`)
  - Notify the user a move is about to be made, and give them the option to abort. Emphasize that symlinks will be broken and make it abundantly clear that files will be moved.
  - Move it to a folder that has no chance of conflict, such as `./.data/nataili`
  - Notify the user of the new location.
  - Set `NATAILI_CACHE_DIR` to the new data folder, IE `NATAILI_CACHE_DIR=./.data/`
    - Further, this may be an opportunity to do the same for `ray/`.
  - There are a couple of lines which catch a small corner case to do with this directory, they can be removed as the case it addresses could be obsoleted by this set of changes.

- Code which identifies if the the folder `nataili/` exists, but the worker is not currently configured to use it or it appears to be empty
  - Warn the user, but take no action

**Comment by db0** [comment]
Sure, go ahead. I had already written similar code for this during the migration to nataili 0.2.0, so you should be able to re-use it
