### ISSUE TITLE
help: cuInit results in UNKNOWN_CUDA_ERROR

### ISSUE THREAD

**Issue by Ox2098** [Haidra-Org/AI-Horde-Worker#157]
My computer has an RTX 2070 graphics card and everything runs fine with SDWEBUI. I am using a virtual environment with miniconda3. However, after installing AI Horde, I am getting an error. What could be the reason for this?

-----------------

(horde-worker) ox2098@DAN:~/AI-Horde-Worker$ sh horde-bridge.sh 
Traceback (most recent call last):
  File "/home/ox2098/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 247, in ensure_initialized
    self.cuInit(0)
  File "/home/ox2098/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 320, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/ox2098/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 388, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [34] Call to cuInit results in UNKNOWN_CUDA_ERROR

**Comment by db0** [comment]
have you run `update-runtime.sh`?

**Comment by tazlin** [comment]
> My computer has an RTX 2070 graphics card and everything runs fine with SDWEBUI. I am using a virtual environment with miniconda3. However, after installing AI Horde, I am getting an error. What could be the reason for this?
> 
> (horde-worker) ox2098@DAN:~/AI-Horde-Worker$ sh horde-bridge.sh Traceback (most recent call last): File "/home/ox2098/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 247, in ensure_initialized self.cuInit(0) File "/home/ox2098/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 320, in safe_cuda_api_call self._check_ctypes_error(fname, retcode) File "/home/ox2098/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 388, in _check_ctypes_error raise CudaAPIError(retcode, msg) numba.cuda.cudadrv.driver.CudaAPIError: [34] Call to cuInit results in UNKNOWN_CUDA_ERROR

If you're using your own python environment, please note that the horde ordinarily assumes that the conda package `cudatoolkit` is installed (as that is part of the installer `update-runtime.sh`). The horde will create its own environment with that shell script and the you can run it through that environment with the other provided shell scripts.
