### ISSUE TITLE
Lora models ?

### ISSUE THREAD

**Issue by pastuh** [Haidra-Org/AI-Horde-Worker#179]
Can't find any information about Lora models.
Is it possible to use them? If so, in which folder to upload the file and activate?

**Comment by db0** [comment]
Not yet but will be possible once https://github.com/db0/AI-Horde-Worker/pull/146 is merged

**Comment by jug-dev** [comment]
This is being tracked here: https://github.com/orgs/Haidra-Org/projects/3
