### ISSUE TITLE
Pruned models

### ISSUE THREAD

**Issue by woct0rdho** [Haidra-Org/AI-Horde-Worker#25]
It would be good if we maintain a curated collection of pruned models, as we only need to do inference in this project. Currently some downloaded models are as large as 7 GB, while a pruned, fp16 quantized, VAE merged model only takes 2 GB, which reduces VRAM usage and helps serve multiple models on mid-tier gaming GPUs.

(If multiple models use the same VAE, splitting out the VAE can additionally save 0.2 GB for each model, but I think that's negligible.)

**Comment by AlRlC** [comment]
Models were added to the db as soon as they became available. Unfortunately some models that are posted publicly don't have pruned versions already available, so we'll need to prune and re-upload those models. I can work on this soon 👍

**Comment by jug-dev** [comment]
Closing this as most models these days are just linking directly to civitai, there are over 200 of them and they change frequently
