### ISSUE TITLE
Could not pick default device error when running horde-alchemist-bridge.sh (CPU only)

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Haidra-Org/AI-Horde-Worker#252]
I'm not qualified, so here we go. When I run horde-alchemist-bridge.sh, the script refuses to pick the CPU, and complains saying "Could not pick default device". It then runs normally, and softlocks as it can't use the CPU. How do I specify a device to use (in this case, the CPU)?

**Comment by db0** [comment]
Hello, we prefer that people don't use just CPU for alchemists. Even for the simplest captioning, the time needed is too large

**Comment by TheSystemGuy1337** [comment]
I only have an AMD GPU, which is impossible to use due to lack of decent compute support. Guess I’m stuck with 14 kudos which is equivalent to anon access.On Jun 16, 2023, at 11:17 AM, Divided by Zer0 ***@***.***> wrote:﻿
Hello, we prefer that people don't use just CPU for alchemists. Even for the simplest captioning, the time needed is too large

**Comment by TheSystemGuy1337** [comment]
Somehow this issue didn't get closed. Therefore I am yanking the plug for you.
