### ISSUE TITLE
Alchemist worker will download images directly from the internet?

### ISSUE THREAD

**Issue by carcinocron** [Haidra-Org/AI-Horde-Worker#274]
This text is ambiguous about what the type of image downloading (and therefor the risk(s)) are.

> Warning: Currently the Alchemist worker will download images directly from the internet, as if you're visiting a webpage. If this is a concern to you, do not run this worker type. We are working on setting up a proxy to avoid that.

- is this a concern about metered bandwidth usage or possible local network saturation?
- Does the worker conduct scraping of 3rd party websites without the consent of 3rd parties?
- is the "image downloading" just a simple HTTP request or does it involve headless simulation of a browser?

**Comment by tazlin** [comment]
The image downloaded happens through a simple http request. Any perceived or real risk stems entirely from that. The warning is a courtesy to anyone who is exceptionally privacy concerned, as that process may 'leak' your IP, but as noted, it is no different than browsing the internet.

**Comment by tazlin** [comment]
As for 'scraping third parties without their consent', no such behavior exists. The user specifies a single image which the interrogator evaluates.
