### ISSUE TITLE
Problem with ' in Git pathname when cloning repository

### ISSUE THREAD

**Issue by Amoranemix** [Haidra-Org/AI-Horde-Worker#276]
Dear community,

I tried to follow the instructions on https://github.com/Haidra-Org/AI-Horde-Worker#readme
to become a Kobold worker, but they didn’t work: see https://www.reddit.com/r/SillyTavernAI/comments/14xku2r/kobold_horde_worker_installation_error

I got not answer, but finally I reïnstalled a slightly more recent version of Gid in a folder that had no spaces and not ‘ in the pathname. Then cloning repository seemed to work.

If the ‘ is indeed the cause of the error, then there are two problems
- The bug that pathnames are not accepted and the error message not explaining that is the problem.
- The guide pretending there is no such bug.

Edit: The rest of the 'instructions' in the guide don't work either.

**Comment by tazlin** [comment]
Issue Transferred.

**Comment by db0** [comment]
Right, forgot we can do that now :D

**Comment by tazlin** [comment]
Having reviewed the issue, it appears to be rooted in git, and is beyond our ability to readily fix at this time. I recommend you avoid quote characters of any kind in a path when using our, or any, software.

**Comment by Amoranemix** [comment]
If the bug can't be fixed, surely the the guide can?
Isn't it possible to let the guide explain how let one's PC serve as a worker?

**Comment by tazlin** [comment]
Sorry for the inconvenience. As far as I am aware, you are the first person reporting this issue in 9+ months. If it becomes a more persistent issue, we can address it more robustly then.
