### ISSUE TITLE
[QUESTION]: Checkpoint folder(s)?

### ISSUE THREAD

**Issue by Woisek** [Haidra-Org/AI-Horde-Worker#277]
I just installed Horde Worker and started it. I saw, that it wanted to download some checkpoints.. I aborted this because I have checkpoints. I noticed, that I haven't seen any option to select a path to my checkpoint folder.
So ... where is/can this be set? And how does the worker detect the models?
I rename and, if needed, prune some models for organizational reasons and to save space.

Any hints on that, please? 🤔

**Comment by tazlin** [comment]
The worker defaults to the models folder in the AI-Horde-Worker folder. Unfortunately, only predetermined specific modes can be offered. If you want to save space, I recommend you only pick one or two popular models. The worker does not support custom file names or unknown models.

**Comment by Woisek** [comment]
> The worker defaults to the models folder in the AI-Horde-Worker folder.

How is this folder named? The only 'model' related folder is named horde_model_reference, but I don't think that this is it.

> Unfortunately, only predetermined specific models can be offered

Well, I have those checkpoints. They just not named so <strike>stupidly</strike> bad.

>The worker does not support custom file names or unknown models.

Then this would be an good update, I guess. 🙂

Thanks for checking in.

**Comment by tazlin** [comment]
If you had a an older version of the worker, the folder may be named nataili.

**Comment by Woisek** [comment]
I have indeed this folder, but I installed this fresh today. How can it be 'older'? 🤔
And in there goes the folder(s) with the checkpoints I assume.

**Comment by tazlin** [comment]
You are probably better off not trying to manually add models. Use the config for the worker and allow it to download and manage everything:

**Comment by Woisek** [comment]
Thanks for your advice, but don't you think that this is all a bit cumbersome and not-so-userfriendly? I mean, I did this now to help with what I got already, to give back to the community and not to get waste more time and space. The install alone was again several GB big.
Don't get me wrong, I find the horde concept as such a great one. But right now, I'm not so convinced anymore if I should contribute to it when contributing is such a problem with several hurdles.

But thanks from all of us that you made this work nevertheless.

**Comment by tazlin** [comment]
Sorry that you feel that way. We rely on community volunteer support made in good faith. We are volunteers ourself and do the best we can given the limited resources we have.

If you ever find that you can dedicate more time to working within the constraints available, feel feee to return.

**Comment by Woisek** [comment]
I can suggest something if you wish, regarding the models.
Because you mentioned 'custom file names' (but I don't know how it works on your side): You don't necessarily need to rely on file names. You could use the hash of the models. Maybe you could use the same hash check like in https://github.com/mix1009/model-keyword that rely also on hashes. That way, it would not matter what name the model has.

Just an idea. 🙂

**Comment by tazlin** [comment]
The files are already identified by hash. As for the file name specificity, removing that hurdle is part of an upcoming version.

**Comment by Woisek** [comment]
Cool. And how about the custom folder where models can be scanned and matching ones separately displayed for selecting? Is this a thing?

**Comment by tazlin** [comment]
It is on the roadmap for a future version.

**Comment by Woisek** [comment]
Nice, I'm looking forward to it, thanks. 👍
