### ISSUE TITLE
tryning api with 0000000000 or with key given at https://stablehorde.net/registerdoes not work

### ISSUE THREAD

**Issue by scenaristeur** [Haidra-Org/AI-Horde-Worker#306]
Hi, 
new to Horde, i've tried the api at https://stablehorde.net/api/ with /v2/generate/text/async

even with 0000000000 or with a registered API key i got same result 

```
{
  "message": "Worker with ID 'string' not found. You have requested this URI [/api/v2/generate/text/async] but did you mean /api/v2/generate/text/async or /api/v2/generate/async or /api/v2/generate/text/pop ?"
}
```
![Screenshot 2023-10-01 at 17-31-56 AI Horde](https://github.com/Haidra-Org/AI-Horde-Worker/assets/4020744/337aadb5-89e1-49f0-aeb7-55daccf7fec5)

![Screenshot 2023-10-01 at 17-28-30 AI Horde](https://github.com/Haidra-Org/AI-Horde-Worker/assets/4020744/800dbec4-c30a-47a7-8946-59d6ed7ce49c)

**Comment by db0** [comment]
Do not send all the parameters at their example values, if you're not using them. Only send the exact parameters you want to use, and only if you understand what they're doing.
