### ISSUE TITLE
Is there a way to run this from an ARM device?

### ISSUE THREAD

**Issue by everypizza1** [Haidra-Org/AI-Horde-Worker#310]
My phone has a pretty good GPU, but is ARM and not rooted. Is there a way to run this from there?

**Comment by db0** [comment]
Not really atm. Can it run ComfyUI?

**Comment by everypizza1** [comment]
Probably not. Would there be a way to just use the Alchemy bridge?

**Comment by db0** [comment]
Can you run arbitrary python code in it?

**Comment by everypizza1** [comment]
Yes, through PyDroid

**Comment by db0** [comment]
The current alchemist is set to run via cuda, so it needs an nvidia, but we're working on updated code, which might allow to run. However I wouldn't hold my breath. Our target hardware were never really mobile phones.

**Comment by everypizza1** [comment]
I'll just run this from my computer for now.
