### ISSUE TITLE
OpenAI API support

### ISSUE THREAD

**Issue by Anthonyg5005** [Haidra-Org/AI-Horde-Worker#319]
I think it'd be a good idea to support it as I'd like to be able to use [Text-gen-webui](https://github.com/oobabooga/text-generation-webui) instead of [KoboldAI](https://github.com/henk717/KoboldAI) as I get a 4x increase in performance. I know there's a pull request for it but #278 uses an outdated API.

**Comment by db0** [comment]
If you're interested in performance, you need to look into aphrodite as you'll get 10x the performance easily https://github.com/PygmalionAI/aphrodite-engine

Alternatively koboldcpp is also blazing fast

**Comment by Anthonyg5005** [comment]
Seems like I'll use koboldcpp. Tried aphrodite but it took hours to get working and awq wasn't worth it. While the gguf gave me a bit lower accuracy, it is similar speed to what I was getting with exl2

**Comment by Anthonyg5005** [comment]
Seems like aphrodite got exl2 support
