### ISSUE TITLE
pix2pix jobs failing due to tensor size mismatch

### ISSUE THREAD

**Issue by JodanJodan** [Haidra-Org/AI-Horde-Worker#86]
[trace.log](https://github.com/db0/AI-Horde-Worker/files/10924703/trace.log) : `RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 154 but got size 77 for tensor number 1 in the list.`

[trace.log](https://github.com/db0/AI-Horde-Worker/files/10946696/trace.log) : Still occurring on commit 15ddf6a

[trace.log](https://github.com/db0/AI-Horde-Worker/files/11007455/trace.log) : Still occurring on commit 5570f93

**Comment by tazlin** [comment]
This issue is moot due to the comfy switch. Any new issues relating to pix2pix will be necessarily be unrelated.
